### ISSUE TITLE
Make user's OAuth token accessible to Jenkins pipelines

### ISSUE THREAD

**Issue by omallo** [openshift/jenkins-openshift-login-plugin#10]
I'm implementing a Jenkins pipeline which deploys an application on multiple stages (DEV, TEST, PROD).

The deployment to TEST and PROD must be manually confirmed by an authorized user within Jenkins. When the user confirms the deployment within Jenkins, I would like to trigger the deployment on the OpenShift cluster using the OAuth token of the currently logged in user.

Is it somehow possible to access the OAuth token of the currently logged in user when using the OpenShift login plugin?

**Comment by gabemontero** [comment]
The credential is stored in the http session:  https://github.com/openshift/jenkins-openshift-login-plugin/blob/master/src/main/java/org/openshift/jenkins/plugins/openshiftlogin/OAuthSession.java#L82

You should be able to drop into Java in you pipeline job and get it from there in the same fashion via the Stapler class.

@bparees - FYI - perhaps a burgeoning scenario to consider

**Comment by omallo** [comment]
I don't think that a HTTP session will be available while the a Jenkins pipeline is executing. A quick try calling `Stapler.getCurrentRequest()` confirms this since the method returns `null`. Did you mean accessing it that way?

**Comment by gabemontero** [comment]
Yep `Stapler...` is what I was referring to.  And yep, now that you mention it, I think I vaguely remember the `Stapler...` stuff not being accessible from within a pipeline.

We do already add a UserProperty to the User object in the oauth login code today (surfaces the email registered for the user in OpenShift for example).

It does not include the Oauth credential, but In theory, we could add an additional UserProperty that includes the Credential information for the user to access in a fashion similar to the link you noted.

I think it is worth a discussion as a request for new function within openshift dev.  At first blush though, while easy to implement, I'm not 100% sure if exposing the Credential in such a way won't displease our security watch dogs.  But again, we can have the discussion.

I've opened https://trello.com/c/MQDa3BWB/1157-make-user-s-oauth-token-accessible-to-jenkins-pipelines to facilitate review of this requirement request.

thanks

**Comment by bparees** [comment]
Tokens are only valid within a single cluster so the token that's used to login to jenkins is not going to have access to more than one cluster, so it can't be used for promoting apps across clusters.  As such implementing this doens't seem like it would solve the scenario in question.  We've archived the card that was created to implement it.  @omallo let us know if you want to discuss further but right now I don't see an obvious path to what you want (tying the token of the user who approved the change, to the actual action that promotes the change).  You can of course use the jenkins credential store to store other credentials to be used to access the prod cluster and perform the promotion, but i realize that's not quite the same as what you were after.
