### ISSUE TITLE
Setting "E-mail address" field in Jenkins

### ISSUE THREAD

**Issue by racodond** [openshift/jenkins-openshift-login-plugin#100]
Hi,

I'm using version 1.0.22 of the OpenShift Login plugin. From Jenkins Update Center, it redirects to this fork: https://github.com/jenkinsci/openshift-login-plugin. But there's no way to create an issue from there. So, I'm posting here. Both repos seem to be in sync. So, which one is the right one? I'm a bit lost.

When I log in to Jenkins through this plugin, it creates my user but the "E-mail address" field is empty. Is there any way to fill up this field with the information from OpenShift?
oc get identities/ldap_provider:drn -o yaml
apiVersion: user.openshift.io/v1
extra:
  email: john.smith@corp.com
  name: John Smith
  preferred_username: jsm
kind: Identity
metadata:
  creationTimestamp: 2018-11-06T13:14:19Z
  name: ldap_provider:jsm
  resourceVersion: "30942493"
  selfLink: /apis/user.openshift.io/v1/identities/ldap_provider%3Adrn
  uid: ded416ec-e1c5-11e8-a4f2-005056920908
providerName: ldap_provider
providerUserName: jsm
user:
  name: jsm
  uid: ded3c766-e1c5-11e8-a4f2-005056920908

Thank you

Regards,

David

**Comment by racodond** [comment]
Hi,

Any feedback on this matter?

Thank you

Regards,

David

**Comment by akram** [comment]
Hi @racodond ,

email is already supposed to be filled by information gathered from OpenShift:
https://github.com/jenkinsci/openshift-login-plugin/blob/master/src/main/java/org/openshift/jenkins/plugins/openshiftlogin/OpenShiftUserInfo.java#L76

The value of this field is mapped from the `oc get user` .
Can you check what you have there?
