### ISSUE TITLE
Bypass "Log in with OpenShift" message

### ISSUE THREAD

**Issue by fart20** [openshift/jenkins-openshift-login-plugin#103]
At work, they have set up a Jenkins instance with your plugin installed. When I want to access a site (e.g. by clicking my bookmark to the status page each morning) I am presented with a login button. When I click it, some redirection and SSO magic happens and I am logged in.

This step is annoying and feels unnecessary. Is there a way to configure the plugin that this "login screen" is automatically bypassed? I.e. instead of having me press the button manually, I would like this to happen automatically.

I'm talking about this message: https://github.com/openshift/jenkins-openshift-login-plugin/blob/master/src/main/resources/org/openshift/jenkins/plugins/openshiftlogin/openshift-jenkins.html

**Comment by akram** [comment]
Hi @fart20 ,

you can bypass the redirect prompt by setting the environment variable OPENSHIFT_ENABLE_REDIRECT_PROMPT=false in the Jenkins deployment.

```
oc set env dc/jenkins OPENSHIFT_ENABLE_REDIRECT_PROMPT
```
or during installation:

```
oc new-app jenkins-persistent -e OPENSHIFT_ENABLE_REDIRECT_PROMPT=false
```
