### ISSUE TITLE
Jenkins keep looping user back to the login page

### ISSUE THREAD

**Issue by huzhou** [openshift/jenkins-openshift-login-plugin#106]
Hello

Today I try to use the **openshift-jenkins-login-plugin-config** config map to do the access control and I got some weird behavior.
Basically I have two openshift role: **admin** and **user**, admin is the namespace admin role and user is a role that only allow to start a build and view build logs. Then I have the configmap setup as follow
```sh
- apiVersion: v1
  data:
    Job-Build: user
    Job-Read: user
    Overall-Administer: admin
  kind: ConfigMap
```
After the configmap is applied, I tested by login to the Jenkins UI and check that user with **admin** role has the Overall-Administer jenkins permission as expected. However, user with the **user** role cannot even login into the Jenkins UI. Jenkins just keep looping the user back to the login page. Is this something expected?

Openshift version: Openshift 3.7/3.11
Jenkins: Using the jenkins-ephemeral template

**Comment by akram** [comment]
Hi @huzhou , which version of openshift-login plugin are you using?

**Comment by huzhou** [comment]
I believe it is 1.0.19

**Comment by akram** [comment]
do you have the ability to try to latest which s 1.0.24 or even 1.0.23 which is the latest tested with openshift 3.11 ?

**Comment by huzhou** [comment]
okay I will try to update that plugin to 1.0.24 and get back to you once I tested! Thanks!

**Comment by akram** [comment]
@huzhou any update?
