### ISSUE TITLE
Plugin enhancement for integrating OpenShift user groups into Jenkins SecurityRealm implementation

### ISSUE THREAD

**Issue by lukas-smiga** [openshift/jenkins-openshift-login-plugin#108]
Hi Community!

We are currently in the process of implementing a feature required by our customer into Jenkins OCP login plugin so the development teams can use OpenShift groups (i.e. synced from LDAP/AD) for permission granting. Part of the requirements was, if possible, to downstream the changes back to the plugin community. As the main implementor of these changes it is my assignment and pleasure to start doing so.

The changes are observable under our fork and branch here: [https://github.com/elos-tech/jenkins-openshift-login-plugin/tree/RBO2-78](https://github.com/elos-tech/jenkins-openshift-login-plugin/tree/RBO2-78). So far, the changes are consisting of adding required implementations of abstract SecurityRealm (and other) methods, against OCP REST API. We tried to mix the existing behaviour with new functionality and there are some decisions to be made – as well as some solid refactoring and testing 😊. 

If there is community/maintainer interest, we would appreciate any help or guidance leading to successful pull-request.

Thanks for any feedback regarding such steps.
L.

**Comment by akram** [comment]
Hi @lukas-smiga , thanks for reaching out.

I am sure there will be interest from the community of users. And, as maintainers we are also interrested in  trying to get this merged.

We understand that a huge refactoring may be required. If you look at the history, the SecurityRealm class is indeed quite old and too big. And refactoring it, is not without risks. As we have many customers using the plugin in production we want to be careful with that.

As an alternate solution, now, OCP users can still use the LDAP group sync feature , and then perform manual groups assignment for some role. And, indeed, that's a bit handy.
So, an LDAP group based mechanism can for sure help.

Let us know about your achievements, and if you need some help, please feel free to reach out here.
