### ISSUE TITLE
create credentials / cumb issuer authenticated as annonymous

### ISSUE THREAD

**Issue by a1dutch** [openshift/jenkins-openshift-login-plugin#118]
Hi,

I am trying to use a jenkins service account to add a credential to the following url (/credentials/store/system/domain/_/createCredentials) but this requires a crumb field.  Should this work without a crumb using the bearer token?

Generating a crumb using the following url returning an announymous

```
curl 'https://<jenkins url>/crumbIssuer/api/json' -H 'Authorization Bearer <bearer token>'
```

the error returned is `HTTP/1.1 403 Forbidden` with the following headers

```
X-Jenkins: 2.263.3
X-You-Are-Authenticated-As: anonymous
X-You-Are-In-Group-Disabled: JENKINS-39402: use -Dhudson.security.AccessDeniedException2.REPORT_GROUP_HEADERS=true or use /whoAmI to diagnose
X-Required-Permission: hudson.model.Hudson.Read
X-Permission-Implied-By: hudson.security.Permission.GenericRead
X-Permission-Implied-By: hudson.model.Hudson.Administer
```

Is there some configuration we are missing? config map is below.

```
{
    "apiVersion": "v1",
    "data": {
        "Overall-Administer": "admin,edit",
        "Overall-Read": "view"
    },
    "kind": "ConfigMap",
    "metadata": {
        "annotations": {},
        "name": "openshift-jenkins-login-plugin-config",
        "namespace": "test"
    }
}
```

Cheers

Andy

**Comment by a1dutch** [comment]
possibly releated to https://issues.jenkins.io/browse/JENKINS-55157

**Comment by ckristo** [comment]
Seems this problem still persists in the latest version (v1.1.0.248.v1908df5c4f5e)
