### ISSUE TITLE
Permission mapping - support IDs with spaces

### ISSUE THREAD

**Issue by jemerald** [openshift/jenkins-openshift-login-plugin#123]
The [lockable resources](https://plugins.jenkins.io/lockable-resources/) plugin adds the `Lockable Resources` permission group.

Permission mapping for this group currently could not be customised, because space character is not valid as a config key in the config map.

> `Error "Invalid value: "Lockable Resources-View": a valid config key must consist of alphanumeric characters, '-', '_' or '.' (e.g. 'key.name', or 'KEY_NAME', or 'key-name', regex used for validation is '[-._a-zA-Z0-9]+')" for field "data[Lockable Resources-View]".`

Please add a work around for this in the permission ID matching - either remove the spaces or replace them with underscores, so the mapping can be customised with either:

```yaml
  LockableResources-View": 'view,edit,admin'
```

or

```yaml
  Lockable_Resources-View": 'view,edit,admin'
```

**Comment by jonesbusy** [comment]
Hi,

Same issue here.

We are using config map to setup permission.

We need to support the Lockable Resources.

Thanks

**Comment by jonesbusy** [comment]
I've submited a PR here : https://github.com/openshift/jenkins-openshift-login-plugin/pull/128

I hope someone will take a look at it.
