### ISSUE TITLE
Two instances in the same namespace use the same ConfigMap for permission mapping

### ISSUE THREAD

**Issue by stef-h** [openshift/jenkins-openshift-login-plugin#144]
The OpenShiftOAuth2SecurityRealm has the name of the ConfigMap for permission mapping hard-coded into the CONFIG_MAP_URI field ("openshift-jenkins-login-plugin-config"):

https://github.com/openshift/jenkins-openshift-login-plugin/blob/master/src/main/java/org/openshift/jenkins/plugins/openshiftlogin/OpenShiftOAuth2SecurityRealm.java#L152

`private static final String CONFIG_MAP_URI = "/api/v1/namespaces/%s/configmaps/openshift-jenkins-login-plugin-config";`

We would like to set the name of the ConfigMap via environment variables in order to have more than one Jenkins instance in the same namespace with different permission mapping ConfigMaps.

**Comment by stef-h** [comment]
Here is an example how the change could look like (built and tested locally):

https://github.com/stef-h/jenkins-openshift-login-plugin/commit/a79ed5f159d13ec9266d6dd999233acbe038c4e5

**Comment by coreydaley** [comment]
I think something like that would work, please submit a pull request and we will review it.
