### ISSUE TITLE
real admin

### ISSUE THREAD

**Issue by jr00n** [openshift/jenkins-openshift-login-plugin#18]
Hi, how can I become the real admin in Jenkins when this plugin is enabled?

**Comment by gabemontero** [comment]
The user you are logging in with must have the `admin` role in the OpenShift project that Jenkins is authenticating against.

The first paragraph at https://github.com/openshift/jenkins-openshift-login-plugin#openshift-role-to-jenkins-permission-mapping describes this.

To learn how to add the OpenShift admin role to a user, see https://docs.openshift.org/latest/admin_guide/manage_authorization_policy.html#managing-role-bindings
