### ISSUE TITLE
Troubles authenticating using jenkins job builder

### ISSUE THREAD

**Issue by gregswift** [openshift/jenkins-openshift-login-plugin#20]
Hey. We've got a few sets of users who want to bring over some of their more classic jobs into their openshift jenkins using jenkins job builder.  However we've tried several different passwords and no luck..  Specifically:

Trying both the user-role and just user as the username we tried:

* standard password (didn't expect this to work)
* the token from `oc whoami -t`
* the token from `oc describe secret jenkins-token-*`

Consistently got the following:

```
Traceback (most recent call last):
  File "/usr/lib/python3.5/site-packages/jenkins/__init__.py", line 430, in jenkins_open
    response = urlopen(req, timeout=self.timeout).read()
  File "/usr/lib64/python3.5/urllib/request.py", line 163, in urlopen
    return opener.open(url, data, timeout)
  File "/usr/lib64/python3.5/urllib/request.py", line 472, in open
    response = meth(req, response)
  File "/usr/lib64/python3.5/urllib/request.py", line 582, in http_response
    'http', request, response, code, msg, hdrs)
  File "/usr/lib64/python3.5/urllib/request.py", line 510, in error
    return self._call_chain(*args)
  File "/usr/lib64/python3.5/urllib/request.py", line 444, in _call_chain
    result = func(*args)
  File "/usr/lib64/python3.5/urllib/request.py", line 590, in http_error_default
    raise HTTPError(req.full_url, code, msg, hdrs, fp)
urllib.error.HTTPError: HTTP Error 401: Invalid password/token for user: me-jenkins

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/usr/bin/jenkins-jobs", line 10, in <module>
    sys.exit(main())
  File "/usr/lib/python3.5/site-packages/jenkins_jobs/cmd.py", line 171, in main
    execute(options, config)
  File "/usr/lib/python3.5/site-packages/jenkins_jobs/cmd.py", line 330, in execute
    options.names)
  File "/usr/lib/python3.5/site-packages/jenkins_jobs/builder.py", line 355, in update_job
    if (self.jenkins.is_job(job.name)
  File "/usr/lib/python3.5/site-packages/jenkins_jobs/builder.py", line 147, in is_job
    if job_name in self.job_list:
  File "/usr/lib/python3.5/site-packages/jenkins_jobs/builder.py", line 134, in job_list
    self._job_list = set(job['name'] for job in self.jobs)
  File "/usr/lib/python3.5/site-packages/jenkins_jobs/builder.py", line 127, in jobs
    self._jobs = self.jenkins.get_jobs()
  File "/usr/lib/python3.5/site-packages/jenkins/__init__.py", line 764, in get_jobs
    return self.get_all_jobs(folder_depth=folder_depth)
  File "/usr/lib/python3.5/site-packages/jenkins/__init__.py", line 813, in get_all_jobs
    jobs = [(0, "", self.get_info(query=JOBS_QUERY)['jobs'])]
  File "/usr/lib/python3.5/site-packages/jenkins/__init__.py", line 550, in get_info
    Request(self._build_url(url))
  File "/usr/lib/python3.5/site-packages/jenkins/__init__.py", line 429, in jenkins_open
    self.maybe_add_crumb(req)
  File "/usr/lib/python3.5/site-packages/jenkins/__init__.py", line 302, in maybe_add_crumb
    self._build_url(CRUMB_URL)), add_crumb=False)
  File "/usr/lib/python3.5/site-packages/jenkins/__init__.py", line 447, in jenkins_open
    e.code, e.msg)
jenkins.JenkinsException: Error in request. Possibly authentication failed [401]: Invalid password/token for user: me-admin
```

Any suggestions?

**Comment by gabemontero** [comment]
Hey @gregswift 

The answer could go in a series of directions based on how old various pieces of software are and the nature of the env.

Simplest answer will be if you are a) running on something from this calendar year, then
a) running jenkins outside of an openshift pod, the `admin` user id will literally have `password` as its password, per https://github.com/openshift/jenkins#jenkins-admin-user, unless they override it with the JENKINS_PASSWORD env var
b) running jenkins inside an openshift pod, then it is your openshift credentials; users should use the same ID and password they log onto the openshift console with

More doc at https://docs.openshift.org/latest/using_images/other_images/jenkins.html#jenkins-initializing-jenkins

So:
- what version of the openshift jenkins image are they using?
- what version of openshift are they running against?
- what version of the example openshift jenkins template might they have used to start up jenkins?  
- or was the openshift jenkins image started via `docker run ...`
- or was the login plugin installed into an existing jenkins deployment (no openshift jenkins image or openshift pod ) ?

**Comment by gregswift** [comment]
@gabemontero thanks for the quick response. In retrospect I did leave a lot of data out. sorry about that.

* version of openshift jenkins image, says its using jenkins-2-centos:latest here is the sha:
`openshift/jenkins-2-centos7@sha256:25f1e38572b0aed33afdc97d660add9046e5f95f7950bd7db21796403fa21060`
* Openshift is 1.5.1 
* I tried it with the default jenkins persistent template
* its the rolled in plugin for that image

**Comment by gregswift** [comment]
Oh, and i just re-verified, my standard credentials do not work either.

**Comment by gabemontero** [comment]
OK, then we'll need the next level of debug data:
1) the jenkns pod logs
2) oc get sa jenkins -o yaml ... confirm the oauth whitelist annotation is correct
3) the openshift master logs

There have been a few known gotchas, especially if the cluster has gone through an upgrade.  Typically that set of data has allowed us to uncover it.

@enj fyi

**Comment by gregswift** [comment]
This cluster was upgraded from 1.4 to 1.5, so maybe the issue stems from there. I'll get these logs to you soon.

**Comment by gabemontero** [comment]
Ah yeah, there are some reconciliation commands that you have to run for the oauth stuff to work.

I believe https://docs.openshift.com/enterprise/3.0/architecture/additional_concepts/authorization.html#updating-cluster-roles properly explains it, but @enj can keep my honest if that is not correct.

**Comment by enj** [comment]
Upgrading via openshift ansible will run these reconcile commands:

https://github.com/openshift/openshift-ansible/blob/master/playbooks/common/openshift-cluster/upgrades/upgrade_control_plane.yml

Note that `--confirm` defaults to `false` so running the command without any parameters will show you the dry-run output, and thus allow you to determine if anything is going to change.

**Comment by gregswift** [comment]
```
# oc logs -f jenkins-1-5vd7z
Aug 11, 2017 8:12:22 PM org.openshift.jenkins.plugins.openshiftlogin.OpenShiftOAuth2SecurityRealm populateDefaults
INFO: OpenShift OAuth: provider: OpenShiftProviderInfo: issuer: https://openshift.example.com:443 auth ep: https://openshift.example.com:443/oauth/authorize token ep: https://openshift.example.com:443/oauth/token
Aug 11, 2017 8:12:22 PM org.openshift.jenkins.plugins.openshiftlogin.OpenShiftOAuth2SecurityRealm populateDefaults
INFO: OpenShift OAuth returning true with namespace greg-jenkins SA dir null default /run/secrets/kubernetes.io/serviceaccount SA name null default jenkins client ID null default system:serviceaccount:greg-jenkins:jenkins secret null default LONG_HASH redirect null default https://openshift.example.com:443 server null default https://openshift.default.svc
```
I am not sure I see a whitelist in the annotations. what should that look like?
```
$ oc get sa jenkins -o yaml 
apiVersion: v1
imagePullSecrets:
- name: jenkins-dockercfg-57pks
kind: ServiceAccount
metadata:
  annotations:
    serviceaccounts.openshift.io/oauth-redirectreference.jenkins: '{"kind":"OAuthRedirectReference","apiVersion":"v1","reference":{"kind":"Route","name":"jenkins"}}'
  creationTimestamp: 2017-08-10T22:01:26Z
  labels:
    app: jenkins-persistent
    template: jenkins-persistent-template
  name: jenkins
  namespace: greg-jenkins
  resourceVersion: "56392042"
  selfLink: /api/v1/namespaces/greg-jenkins/serviceaccounts/jenkins
  uid: 74668bd2-7e17-11e7-98a6-005056170419
secrets:
- name: jenkins-token-ffxvd
- name: jenkins-dockercfg-57pks
```

What logs would you want from the master, cause there are lots ;D Here are the ones that match this project:
```
# journalctl -l | grep greg-jenkins | sed 's/ord1\.prod\.//g; s/rsi\.rackspace\.net/openshift.example.com/g'
Aug 11 20:12:22 node-018.openshift.example.com dockerd-current[1270]: INFO: OpenShift OAuth returning true with namespace greg-jenkins SA dir null default /run/secrets/kubernetes.io/serviceaccount SA name null default jenkins client ID null default system:serviceaccount:greg-jenkins:jenkins secret null default LONG_HASH redirect null default https://openshift.example.com:443 server null default https://openshift.default.svc
Aug 11 20:12:49 node-018.openshift.example.com origin-node[3010]: I0811 20:12:49.604931    3076 node_auth.go:86] Node request attributes: namespace=, user=&user.DefaultInfo{Name:"system:openshift-node-admin", UID:"", Groups:[]string{"system:node-admins", "system:authenticated"}, Extra:map[string][]string(nil)}, attrs=authorizer.DefaultAuthorizationAttributes{Verb:"get", APIVersion:"v1", APIGroup:"", Resource:"nodes/proxy", ResourceName:"node-018.openshift.example.com", RequestAttributes:interface {}(nil), NonResourceURL:false, URL:"/containerLogs/greg-jenkins/jenkins-1-5vd7z/jenkins"}
Aug 11 20:12:49 node-018.openshift.example.com dockerd-current[1270]: I0811 20:12:49.604931    3076 node_auth.go:86] Node request attributes: namespace=, user=&user.DefaultInfo{Name:"system:openshift-node-admin", UID:"", Groups:[]string{"system:node-admins", "system:authenticated"}, Extra:map[string][]string(nil)}, attrs=authorizer.DefaultAuthorizationAttributes{Verb:"get", APIVersion:"v1", APIGroup:"", Resource:"nodes/proxy", ResourceName:"node-018.openshift.example.com", RequestAttributes:interface {}(nil), NonResourceURL:false, URL:"/containerLogs/greg-jenkins/jenkins-1-5vd7z/jenkins"}
Aug 11 20:12:49 node-018.openshift.example.com origin-node[3010]: I0811 20:12:49.614472    3076 server.go:744] GET /containerLogs/greg-jenkins/jenkins-1-5vd7z/jenkins: (9.791458ms) 200 [[Go-http-client/1.1] 10.10.155.41:42908]
Aug 11 20:12:49 node-018.openshift.example.com dockerd-current[1270]: I0811 20:12:49.614472    3076 server.go:744] GET /containerLogs/greg-jenkins/jenkins-1-5vd7z/jenkins: (9.791458ms) 200 [[Go-http-client/1.1] 10.10.155.41:42908]
Aug 11 20:13:12 node-018.openshift.example.com dockerd-current[1270]: I0811 20:13:12.791556    3076 node_auth.go:86] Node request attributes: namespace=, user=&user.DefaultInfo{Name:"system:openshift-node-admin", UID:"", Groups:[]string{"system:node-admins", "system:authenticated"}, Extra:map[string][]string(nil)}, attrs=authorizer.DefaultAuthorizationAttributes{Verb:"get", APIVersion:"v1", APIGroup:"", Resource:"nodes/proxy", ResourceName:"node-018.openshift.example.com", RequestAttributes:interface {}(nil), NonResourceURL:false, URL:"/containerLogs/greg-jenkins/jenkins-1-5vd7z/jenkins"}
Aug 11 20:13:12 node-018.openshift.example.com origin-node[3010]: I0811 20:13:12.791556    3076 node_auth.go:86] Node request attributes: namespace=, user=&user.DefaultInfo{Name:"system:openshift-node-admin", UID:"", Groups:[]string{"system:node-admins", "system:authenticated"}, Extra:map[string][]string(nil)}, attrs=authorizer.DefaultAuthorizationAttributes{Verb:"get", APIVersion:"v1", APIGroup:"", Resource:"nodes/proxy", ResourceName:"node-018.openshift.example.com", RequestAttributes:interface {}(nil), NonResourceURL:false, URL:"/containerLogs/greg-jenkins/jenkins-1-5vd7z/jenkins"}
```

**Comment by enj** [comment]
@gregswift are you able to log in via the browser (to confirm the Jenkins OAuth flow works)?

**Comment by gregswift** [comment]
Yes, logging in works fine

**Comment by gregswift** [comment]
Also.. i've tried out the `oadm policy reconcile-cluster-roles` and it shows nothing wrong... which is sad cause i was hoping that was gonna solve our oauth issue with aggregated logging :(

**Comment by enj** [comment]
OK so I will defer to @gabemontero here as if the browser based flow works, than the OAuth configuration is correct.  I am unfamiliar with the Jenkins job builder and how it would interact with this openshift plugin.  Specifically, how would it know that auth to Jenkins was being deferred to openshift, and thus there is no password (the Jenkins SA is given a scoped token for you and uses that to determine if you can log in).  You could try using that scoped token:

```sh
oc get oauthaccesstoken -o jsonpath='{.items[?(@.clientName=="system:serviceaccount:greg-jenkins:jenkins")].metadata.name}'
```

**Comment by gabemontero** [comment]
Ah - sorry, missed the key aspect of all this that you are trying to login without the jenkins UI / browser (i.e. the browser flow works fine).

First, some quick houseclean:
1) the jenkins pod log looks good, the jenkins / openshift oauth integration is on
2) as does the annotation (I was able to find it)

Without going through the browser to do the oauth proxy / redirect ping pong this plugin provides, the only think that will work out of the box is to set a valid `oc whoami -t` token as a bearer token header (couldn't tell from your description if your use of that token was set as a bearer auth token).  That token needs to at least have view level access to the jenkins namespace.

If done correctly, you'll hit this path in the code:  https://github.com/openshift/jenkins-openshift-login-plugin/blob/master/src/main/java/org/openshift/jenkins/plugins/openshiftlogin/OpenShiftPermissionFilter.java#L146

Most likely you'll need to turn on this LOGGER in jenkins:  https://github.com/openshift/jenkins-openshift-login-plugin/blob/master/src/main/java/org/openshift/jenkins/plugins/openshiftlogin/OpenShiftOAuth2SecurityRealm.java#L108 to see if the token is obtained from the header and we attempt to self-SAR against the jenkins namespace with that token.

If your are hoping to gather a username/password and do the oauth proxy / redirect / ping pong dance to get an oauth token on your own, that is outside the scope of this plugin.

**Comment by gregswift** [comment]
So now i was like 'uhh how do i use a bearer auth token?' and so adding "bearer" to my searches has opened up a whole world of help. will get back to this soon and hopefully be back with an answer!

**Comment by gabemontero** [comment]
hey @gregswift - just doing some house cleaning.  I think we can close this out, correct?  If I am recalling correctly, there was an email thread that detailed how you were able to implement this for your scenario.

**Comment by gabemontero** [comment]
Or maybe I'm getting confused with another user attempting something similar (apologies if that is the case).

**Comment by gabemontero** [comment]
OK, closing out.  Please reopen @gregswift if more assistance is needed.  Thanks.

**Comment by rackergs** [comment]
we were't solved yet but mainly cause i havent had a chance to go back. will reopen if needed. thanks

**Comment by gabemontero** [comment]
On Wed, Oct 11, 2017 at 12:36 PM, Greg Swift <notifications@github.com>
wrote:

> we were't solved yet but mainly cause i havent had a chance to go back.
> will reopen if needed. thanks
>
cool / sounds good
