### ISSUE TITLE
Can this plugin expose the oc tool/rest api token as well?

### ISSUE THREAD

**Issue by paterczm** [openshift/jenkins-openshift-login-plugin#28]
Once authenticated against OpenShift in Jenkins, it would be great to be able to run oc tool commands or call OpenShift rest apis using a token associated with my OpenShift account. Is that feasible? Thanks!

**Comment by gabemontero** [comment]
Hi @paterczm 

Having this plugin somehow "bake in" the token associated with your oauth based login into jenkins is not the form we are proscribing for what you are desiring, nor is something we'll be pursuing.

I've tagged a similar issue in our jenkins-client-plugin for your reference.

A quick summary of that discussion:  the "better architecture" is to create a secret (most likely for a service account that has similar permissions as the user you log into jenkins as) which can either be mounted into the jenkins pod (if you are running jenkins in an openshfit pod), or leverage our new feature with our sync plugin, where it will create a jenkins credential you can then reference.

@bparees - if you have a sec certainly chime in as you see fit.

thanks
