### ISSUE TITLE
Make default Jenkins roles configurable for Openshift OAuth roles

### ISSUE THREAD

**Issue by Lain92** [openshift/jenkins-openshift-login-plugin#36]
Hi everyone,

We are using the login plugin to manage a lot of developer teams.
However, the fixed roles mapped to the Openshift project view-role is still too permissive in Jenkins as we don't want basic viewer to be able to see credentials in Jenkins.
Do you have any plan on making the OAuth-Jenkins mapping role configurable in the plugin?
We'd to rebuild the plugin and maintain it ourselves if it is not possible.

Thanks.

Sincerely,

Lain92

**Comment by gabemontero** [comment]
Hey @Lain92 

I maintain this plugin as well.

Yes there is a standing request for this.  See https://trello.com/c/kDqWZlOH/1207-5-allow-the-openshift-role-to-jenkins-permission-mapping-to-be-configurable-jenkinsintegration

It is not currently scheduled to be worked on.

If you'd like to submit a PR against this repo to implement that feature, I can work with you to make sure it is sufficiently implemented, and then include it in the official version.

**Comment by Lain92** [comment]
Hi @gabemontero,

Nice to hear from you as well on this plugin. I see that the trello hasn't moved for a year so I'll try getting the stuff done on my side and comes back to you if I have enough buffer to implement it enough.
Thank you very much for offering your help. 

Sincerely, 

Lain92

**Comment by gabemontero** [comment]
Sounds good @Lain92 

I'll also note that the openshift.io folks are also looking for something in this area, though they may be good enough with an env var that simply reduces permissions for the edit role.  But that might start lending some weight to that card.

@sthaha fyi ^^

**Comment by sthaha** [comment]
@gabemontero thanks for the notification. 
@Lain92 would be great to have a PR that addresses this issue. This also means we (fabric8) can delete our fork of the plugin.
