### ISSUE TITLE
how to install?

### ISSUE THREAD

**Issue by mikemowgli** [openshift/jenkins-openshift-login-plugin#40]
Hi sir,
I currently have an OpenShift cluster, where users are authenticated against Active Directory (using the SSSD and Apache proxy method).
This works great, but as soon as OpenShift was integrated with AD, I could no longer log into my jenkins pipeline. I assume your plugin aims to fix that. But how to install it?

**Comment by enj** [comment]
@mikemowgli did you follow these docs: https://docs.openshift.org/latest/install_config/advanced_ldap_configuration/sssd_for_ldap_failover.html ?  If so, those docs are incompatible with Jenkins login and are in the process of being updated in https://github.com/openshift/openshift-docs/pull/9070  Once that change merges please follow the new steps to set up SSSD + Apache.

**Comment by gabemontero** [comment]
Thanks @enj 

@mikemowgli as to installing this plugin, you can download it from the jenkins update center.  Or you can use the openshift jenkins image produced from https://github.com/openshift/jenkins, like docker.io/openshift/jenkins-2-centos7.  There are also rhel7 equivalents if you have a subscription.

The plugin is easiest to use when jenkins is running in an OpenShift Pod.  That way, it can pick up all its needed configuration information from a) various information mounted into the pod, b) some interaction with openshift master based on the information mounted in the pod.

You can configure this plugin to run in a Jenkins that is not in an openshift pod.  See the readme for details.

**Comment by mikemowgli** [comment]
@enj Yes I followed that doc. Reading [openshift/openshift-docs#9070](https://github.com/openshift/openshift-docs/pull/9070), it looks this is only about updating the docs, and not about fixing this limitation. So how would jenkins login work ?
Does that mean I need to integrate my OpenShift cluster with AD using [this doc](https://docs.openshift.org/latest/install_config/syncing_groups_with_ldap.html) to be able to login in Jenkins?

**Comment by enj** [comment]
> not about fixing this limitation.

Fixing what limitation?  Everything will work as expected if you follow the updated docs.

> So how would jenkins login work

The same as it always does.  If you deploy Jenkins using our images and have OAuth enabled, the login works as expected.

> using this doc to be able to login in Jenkins

Group sync is unrelated to Jenkins.

**Comment by mikemowgli** [comment]
I only had the time to test it today. It works! Thank you guys!

cheers
