### ISSUE TITLE
Edit role provide cancel job permission

### ISSUE THREAD

**Issue by jmcshane** [openshift/jenkins-openshift-login-plugin#41]
Right now, the permissions are very fixed for what "admin", "edit", and "view" can provide. Would there be a way to customize the permissions matrix for users in these specific roles?

I would like to give our developers Item.CANCEL permission, and in the namespaces that the Jenkins containers are running, the developers have the edit role. Is there any way that I could do this without writing my own update to the code and build the plugin separately?

**Comment by jmcshane** [comment]
Would you be open to a global setting that would provide the cancel permission for the edit role?

**Comment by gabemontero** [comment]
hey @jmcshane - yep, being able to modify the permmissions is a known req currently captured in https://trello.com/c/kDqWZlOH/1207-5-allow-the-openshift-role-to-jenkins-permission-mapping-to-be-configurable-jenkinsintegration

Short term, I would be good with simply adding Item.CANCEL to the admin/edit role for everybody and cutting a new version of this plugin if you want to submit a PR.

**Comment by jmcshane** [comment]
I'll put out a PR now, thank you!

**Comment by gabemontero** [comment]
Cool ... quick heads up, also update the README's section that lists the permissions if you could

**Comment by gabemontero** [comment]
v1.0.9 is available, updating openshift jenkins centos image with https://github.com/openshift/jenkins/pull/631
