### ISSUE TITLE
Jenkins blocks edit role's Jenkins.RUN_SCRIPTS permission without Jenkins.ADMINISTER permission due to matrix-auth-plugin

### ISSUE THREAD

**Issue by andyfeller** [openshift/jenkins-openshift-login-plugin#44]
[org.openshift.jenkins.plugins.openshiftlogin.OpenShiftOAuth2SecurityRealm. updateAuthorizationStrategy()](https://github.com/openshift/jenkins-openshift-login-plugin/blob/master/src/main/java/org/openshift/jenkins/plugins/openshiftlogin/OpenShiftOAuth2SecurityRealm.java#L840) grants those with `edit` OpenShift role the `Jenkins.RUN_SCRIPTS` permission, which I was banking on, however the [jenkinsci/matrix-auth-plugin](https://github.com/jenkinsci/matrix-auth-plugin/blob/master/src/main/resources/hudson/security/DangerousMatrixPermissionsAdministrativeMonitor/message.properties) denies this permission without `Jenkins.ADMINISTER`.  So I'm a little torn because I want the ability to run scripts for edit purposes because my system administrators won't give us `admin` role for service accounts and we need to configure Jenkins in a non-static way.

Thoughts?

**Comment by gabemontero** [comment]
Ooh ... this looks like a recent change in the matrix auth plugin that went out with their 2.3 version.

Our image for example currently pulls in 2.2.  But if we had to upgrade for say a jenkins advisory (a quite likely scenario) we will hit issues running scripts.

I'm leaning towards updating our mapping to add `Jenkins.ADMINISTER` to our edit role, as being able to run scripts is key, sensible mapping between administrator notions be damned.

@bparees opinions?

**Comment by andyfeller** [comment]
Thanks for the follow up @gabemontero! 🙇 

Yeah, we were thinking about adding the `Jenkins.ADMINISTER` permission for OpenShift `edit` role, too; otherwise we'd need a way to override the name of the OpenShift role to translate to Jenkins auth matrix.

**Comment by bparees** [comment]
What distinguishes someone with openshift admin from someone with openshift edit at that point, in terms of their jenkins permissions?

**Comment by andyfeller** [comment]
@bparees : think that is a fair question.  one possible response is that nothing distinguishes them as Overall/Administer is enough to do everything assigned to those with OpenShift `admin` role, so why not make them one in the same.  In this case, then I think the openshift-login plugin should allow someone to decide which OpenShift role(s) match to which Jenkins permissions.

**Comment by gabemontero** [comment]
Nothing as I understand it what `Jenkins.ADMINISTER` means.

Some research needs to be done with the latest combinations about what happens when you remove `Jenkins.RUN_SCRIPTS`.  I recalled that was needed to run pipelines, but that should be confirmed.  Perhaps that is no longer the case.  Looking at core usage today, I believe it is needed for groovy init scripts, which we use today as part of our image startup, and which image extenders are using.  So would have to validate that path as well.

**Comment by bparees** [comment]
yeah i think we need to do that investigation because turning everyone with "edit" permission in openshift into jenkins administrators is going to surprise/upset users of the login plugin, I think.

**Comment by gabemontero** [comment]
Yeah the friction point is:
1) openshift admin vs. edit distinction, vs.
2) ability to leverage needed jenkins functions
3) the apples to oranges comparison to some degree of "admin permissions" between openshift and jenkins

**Comment by andyfeller** [comment]
With `admin` project role, someone can grant rolebindigs to others but also they can affect project node selector and route status, which are some of the major concerns our sysadmins have brought up.  AFAIK OpenShift roles are largely geared towards the systems side and not really application, so I can see a non-OS admin having Jenkins admin capabilities. $0.02

**Comment by gabemontero** [comment]
So I did a test where I removed `Jenkins.RUN_SCRIPTS` from being added, and I was still able to run pipelines, and our init groovy script still ran successfully on startup (the two things I was worried about with removing that permission).

At this point, my $0.02
1) wait to see if we have to bump the matrix plugin from 2.2 to 2.3 cause of a jenkins sec advisory, hence disabling RUN_SCRIPTS for edit users
2) this potential situation is just another reason for implementing https://trello.com/c/kDqWZlOH/1207-5-allow-the-openshift-role-to-jenkins-permission-mapping-to-be-configurable-jenkinsintegration ... I've made reference of this issue there, and mentioned Steve Speicher in the comment

Otherwise, I'm inclinded to keep the status quo wrt admin to admin correlations by default.  I'd really rather see 2) happen, so we can let the users decide on case by case basis.

**Comment by andyfeller** [comment]
Good to know there aren't issues for pipelines or init.groovy.d scripts, but we were trying to have an external process configure plugins via the groovy script console dynamically, so we have to beg an exception until 2) can be done because 1) will/should happen.

**Comment by gabemontero** [comment]
OK, refresh my memory, do you all run out of our openshift jenkins image?

If so, to be clear, unless we bump to 2.3 of the matrix auth plugin in that image, there is no issue.  RUN_SCRIPTS is still allowed for non administrator.  

The enforcement change you found, at least as I've analyzed it, is only in 2.3.  We are still at 2.2.

Unless you see something that says different, or you are not running out of our image, there isn't an issue yet.

If something is amiss with all that, I'd like to understand it certainly.  And if there is, your opinion is understood, but we'll need to have some broader discussions on our end before we agree to changing.

**Comment by andyfeller** [comment]
This did come up with matrix-auth 2.2 so that’s weird.  This is based on the openshift/jenkins image with some dressing around it but here are all the plugins installed including versions:

```
ace-editor:1.1
analysis-core:1.95
antisamy-markup-formatter:1.5
ant:1.8
apache-httpcomponents-client-4-api:4.5.5-2.0
authentication-tokens:1.3
blueocean-autofavorite:1.2.2
blueocean-bitbucket-pipeline:1.5.0
blueocean-commons:1.5.0
blueocean-config:1.5.0
blueocean-core-js:1.5.0
blueocean-dashboard:1.5.0
blueocean-display-url:2.2.0
blueocean-events:1.5.0
blueocean-github-pipeline:1.5.0
blueocean-git-pipeline:1.5.0
blueocean-i18n:1.5.0
blueocean-jira:1.5.0
blueocean:1.5.0
blueocean-jwt:1.5.0
blueocean-personalization:1.5.0
blueocean-pipeline-api-impl:1.5.0
blueocean-pipeline-editor:1.5.0
blueocean-pipeline-scm-api:1.5.0
blueocean-rest-impl:1.5.0
blueocean-rest:1.5.0
blueocean-web:1.5.0
bouncycastle-api:2.16.2
branch-api:2.0.20
checkstyle:3.50
cloudbees-bitbucket-branch-source:2.2.11
cloudbees-folder:6.4
command-launcher:1.2
compress-buildlog:1.2
conditional-buildstep:1.3.6
config-file-provider:2.18
credentials-binding:1.16
credentials:2.1.16
dashboard-view:2.9.11
display-url-api:2.2.0
docker-commons:1.11
docker-workflow:1.15.1
durable-task:1.22
external-monitor-job:1.7
favorite:2.3.1
git-client:2.7.1
github-api:1.90
github-branch-source:2.3.4
github:1.29.0
github-organization-folder:1.6
git:3.8.0
git-server:1.7
greenballs:1.15
handlebars:1.1.1
handy-uri-templates-2-api:2.1.6-1.0
http_request:1.8.22
htmlpublisher:1.16
icon-shim:2.0.3
jackson2-api:2.8.11.1
jacoco:3.0.1
javadoc:1.4
jenkins-design-language:1.5.0
jira:2.5.2
job-dsl:1.69
jquery-detached:1.2.1
jsch:0.1.54.2
junit:1.24
kubernetes-credentials:0.3.1
kubernetes:1.6.0
ldap:1.20
lockable-resources:2.2
mailer:1.21
managed-scripts:1.4
mapdb-api:1.0.9.0
matrix-auth:2.2
matrix-project:1.13
maven-plugin:3.1.2
mercurial:2.3
metrics:3.1.2.11
momentjs:1.1.1
multiple-scms:0.6
node-iterator-api:1.5.0
openshift-client:1.0.12
openshift-login:1.0.8
openshift-pipeline:1.0.54
openshift-sync:1.0.18
pam-auth:1.3
parameterized-trigger:2.35.2
pipeline-build-step:2.7
pipeline-github-lib:1.0
pipeline-githubnotify-step:1.0.4
pipeline-graph-analysis:1.6
pipeline-input-step:2.8
pipeline-milestone-step:1.3.1
pipeline-model-api:1.3.1
pipeline-model-declarative-agent:1.1.1
pipeline-model-definition:1.3.1
pipeline-model-extensions:1.3.1
pipeline-rest-api:2.10
pipeline-stage-step:2.3
pipeline-stage-tags-metadata:1.3.1
pipeline-stage-view:2.10
pipeline-utility-steps:2.0.2
plain-credentials:1.4
project-inheritance:2.0.0
promoted-builds:3.1
pubsub-light:1.12
run-condition:1.0
scm-api:2.2.7
script-security:1.44
slack:2.3
sse-gateway:1.15
ssh-credentials:1.13
ssh-slaves:1.26
structs:1.14
subversion:2.10.5
support-core:2.45.1
timestamper:1.8.9
token-macro:2.5
variant:1.1
vsphere-cloud:2.17
windows-slaves:1.3.1
workflow-aggregator:2.5
workflow-api:2.27
workflow-basic-steps:2.7
workflow-cps-global-lib:2.9
workflow-cps:2.51
workflow-durable-task-step:2.19
workflow-job:2.21
workflow-multibranch:2.18
workflow-remote-loader:1.4
workflow-scm-step:2.6
workflow-step-api:2.14
workflow-support:2.18
rebuild:1.28
```

**Comment by gabemontero** [comment]
Yeah my earlier analysis was incorrect ... https://github.com/jenkinsci/matrix-auth-plugin/commit/246d7d744f7280978546fc67e643f2c950713a87#diff-952cde9367544ea492d3bc075d6b890b is in 2.2

That said, the need for an internal, broader discussion on what we do wrt mapping openshift edit to jenkins admin still needs to occur before I make any changes.  Some folks are out but hopefully that discussion happens later this week.

**Comment by gabemontero** [comment]
Got a PR for configurable role / permission mappings up

**Comment by zonArt** [comment]
Hi,

Thanks for the PR, looks promising. As another point to this implementation, I'll add our use-case:

For some reason, we need to fully remove edit role in the namespace to our users letting them only with view role, but we still want them to be able to create jobs in jenkins. Other scenario I can imagine is if you have some custom roles in your cluster, how would the plugin react to them?

@gabemontero I think your proposition will really help to solve all of the above, thanks again
