### ISSUE TITLE
Request for a configuration field

### ISSUE THREAD

**Issue by piyush-garg** [openshift/jenkins-openshift-login-plugin#48]
Hi,

I am creating this issue to figure out if a configuration field can be provided which will be something like if set true then provide the roles to the user with view rights, similar the roles provided to user with edit rights.

We have created a fork https://github.com/fabric8-jenkins/jenkins-openshift-login-plugin of this plugin, and doing the maintenance like rebase and stuff for a single commit and fix. Details you can find about the feature I am requesting from the single commit we have added to our fork https://github.com/fabric8-jenkins/jenkins-openshift-login-plugin/commit/3c21a257a88925a311d948e16c0e9599f36d9f98

I can provide a PR for this, just want to discuss this first with you.

This will help us to not maintain the fork and use the upstream released version

cc @gabemontero @hrishin

**Comment by gabemontero** [comment]
hey @piyush-garg 

I've got https://github.com/openshift/jenkins-openshift-login-plugin/pull/45 to make the mappings configurable in a way that is openshift centric ... we do *NOT* want to manage this through the Jenkins UI.

I've got higher priority work but hope to get back to that PR in the next few days.  But take a look and let's work through that PR to get to a solution.

**Comment by piyush-garg** [comment]
Thanks a lot, will keep a look at that PR. @gabemontero Again, thanks a lot.

**Comment by gabemontero** [comment]
yw @piyush-garg
