### ISSUE TITLE
Openshift OAuth doesn't work

### ISSUE THREAD

**Issue by Asgoret** [openshift/jenkins-openshift-login-plugin#62]
If i set openshift oauth true i can't login to jenkins. 
Error: 403 Forbidden
Key:  strict-origin-when-cross-origin

**Comment by rajatsingh25aug** [comment]
Can you please provide the steps for reproduce this

**Comment by Asgoret** [comment]
@rajatsingh25aug I install OKD release 3.11 via openshift-ansible and got this error (it was clean install). Yesterday i reset cluster and authentication worked fine.
