### ISSUE TITLE
Support multiple namespaces

### ISSUE THREAD

**Issue by thiagomdiniz** [openshift/jenkins-openshift-login-plugin#65]
Is it possible to define multiple namespaces in the 'namespace' file in some way?
I have an external Jenkins plugged into an OpenShift cluster with multiple projects, so it's not feasible to create a Jenkins for every OpenShift project.

**Comment by gabemontero** [comment]
it is a feature request for sure @thiagomdiniz ... the complication in implementing it stems from injecting the mult project variability into the oauth / self sar flow

It is not something I see happening anytime soon, but I will leave this open for a bit to see if other users chime in.

as an fyi, in your external to openshift jenkins scenarios, other users have created a single project for this plugin to authenticate against, and then created roles that map to each development project, and then added users to each role accordingly.

See https://github.com/openshift/jenkins-openshift-login-plugin#openshift-role-to-jenkins-permission-mapping

this is the current solution provided for your scenario

**Comment by thiagomdiniz** [comment]
@gabemontero , thanks for the answer and the suggested solution.
I've done some tests here and it really seems like the proposed solution will suit us.

I understand that synchronization with multiple projects will add more complexity. I also believe that if we can synchronize multiple projects someday, the Project-based Matrix Authorization strategy will be used in place of the Matrix-based security strategy.

**Comment by gabemontero** [comment]
glad to hear you all have a path @thiagomdiniz 

supporting other auth strategies has also been requested in the past and registered ... it is unclear at this time if/when it will get prioritized  ... non-trivial for sure

@siamaksade @sspeiche @rajatsingh25aug @waveywaves fyi

**Comment by akram** [comment]
As the provided solution works for you I will close this now
/close
