### ISSUE TITLE
Jenkins context "--prefix" is stripped during buildOAuthRedirectUrl(...)

### ISSUE THREAD

**Issue by DizzyThermal** [openshift/jenkins-openshift-login-plugin#69]
When [running Jenkins behind a Reverse Proxy](https://github.com/jenkinsci/docker/blob/master/README.md#configuring-reverse-proxy), a few things needed to be configured:

- `JENKINS_OPTS="--prefix=/jenkins"` context prefix needs to be added to the environment
- The **Jenkins URL** (in Manage Jenkins > Configure System) needs to be appropriately set (i.e., https://secure.apps.example.com/jenkins/)

In `OpenShiftOAuth2SecurityRealm::buildOAuthRedirectUrl(String redirect)`, there is a comment explaining that the redirect URL is being stripped to a "root" url before appending the finishLogin path, however, this is stripping out the added prefix (/jenkins)

This happens on line:
https://github.com/openshift/jenkins-openshift-login-plugin/blob/master/src/main/java/org/openshift/jenkins/plugins/openshiftlogin/OpenShiftOAuth2SecurityRealm.java#L1116

The URL.getHost() strips the prefix out, making my Jenkins URL change from:
https://secure.apps.example.com/jenkins/
to
https://secure.apps.example.com/

If I manually add "/jenkins" to this line, compile, and reinstall the plugin, the OAuth login works and redirects back as expected.

Am I misunderstanding how to handing the OAuth redirecturi, or is it possible to access Jenkins.model (or similar) to check if a --prefix was passed as a startup param/argument and make sure it makes its way to the redirecturi here?

Thanks in advance for the support!

**Comment by rajatsingh25aug** [comment]
Hi @DizzyThermal 
I think I have found a workaround. Please follow these steps and let me know if it worked for you. It worked for me.I'm running Fedora 29 and used `Nginx as a reverse proxy` for this.

-Edit this Jenkins file under sudo `sudo vi /etc/sysconfig/jenkins`

- Scroll down to the very bottom and find the variable `JENKINS_ARGS=""`

- Change it to `JENKINS_ARGS="--prefix=/jenkins"`

- run `sudo service jenkins restart`

- try browsing `http://<ip>:8080/jenkins` (my jenkins is running on port `8080`)

**Comment by rajatsingh25aug** [comment]
Hi @DizzyThermal 
Please follow these steps and let me know if it worked for you. It worked for me.I'm running Fedora 29 and used Nginx to run jenkins as a reverse proxy for this.
I followed here to run jenkins as a reverse proxy here!

-Edit this Jenkins file under sudo sudo vi /etc/sysconfig/jenkins

Scroll down to the very bottom and find the variable JENKINS_ARGS=""

Change it to JENKINS_ARGS="--prefix=/jenkins"

run sudo service jenkins restart

try browsing http://<ip>:8080/jenkins (my jenkins is running on port 8080)

cc @gabemontero  @waveywaves

**Comment by rajatsingh25aug** [comment]
Hi @DizzyThermal 
Please follow these steps and let me know if it worked for you.I'm running Fedora 29 and used Nginx to run jenkins as a reverse proxy for this.
I followed here to run jenkins as a reverse proxy here!

-Edit this Jenkins file under sudo sudo vi /etc/sysconfig/jenkins

Scroll down to the very bottom and find the variable JENKINS_ARGS=""

Change it to JENKINS_ARGS="--prefix=/jenkins"

run sudo service jenkins restart

try browsing http://<ip>:8080/jenkins (my jenkins is running on port 8080)

cc @gabemontero  @waveywaves

**Comment by rajatsingh25aug** [comment]
Hi @DizzyThermal 
Please follow these steps and let me know if it worked for you.I'm running `Fedora 29` and used Nginx to run jenkins behind a  reverse proxy for this.
I followed here to run jenkins as a reverse proxy [here!](http://buildvirtual.net/installing-jenkins-behind-nginx-reverse-proxy/)

-Edit this Jenkins file under `sudo sudo vi /etc/sysconfig/jenkins`

- Scroll down to the very bottom and find the variable `JENKINS_ARGS=""`

- Change it to `JENKINS_ARGS="--prefix=/jenkins"`

- run `sudo service jenkins restart`

- try browsing `http://<ip>:8080/jenkins` (my jenkins is running on port 8080)

cc @gabemontero   @waveywaves

**Comment by rajatsingh25aug** [comment]
Hi @DizzyThermal 
Please follow these steps and let me know if it worked for you.I'm running `Fedora 29` and used **Nginx**.
I followed  [here](http://buildvirtual.net/installing-jenkins-behind-nginx-reverse-proxy/) to run Jenkins behind a reverse proxy

-Edit this Jenkins file under `sudo sudo vi /etc/sysconfig/jenkins`

- Scroll down to the very bottom and find the variable `JENKINS_ARGS=""`

- Change it to `JENKINS_ARGS="--prefix=/jenkins"`

- run `sudo service jenkins restart`

- try browsing `http://<ip>:8080/jenkins` (my jenkins is running on port 8080)

cc @gabemontero  @waveywaves

**Comment by DizzyThermal** [comment]
@rajatsingh25aug thank you for your response, appreciate it.

In my OpenShift Web Console, I navigated to my **jenkins** project, and opened the **Terminal** of the Jenkins pod, however, I'm unable to view or edit `/etc/sysconfig/jenkins` => Permission denied. We are not allowed to run pods as the root user.

I modified the Jenkins App **Environment** to add **JENKINS_ARGS="--prefix=/jenkins"**, similar to how I did JENKINS_OPTS, but the behavior was the same after redeploying with the default jenkins-openshift-login-plugin.

**Comment by rajatsingh25aug** [comment]
@DizzyThermal 
Can you please tell me how did you create Jenkins pod. 

- Did you use any template or any Dockerfile?. 

- How were you able to setup reverse proxy since that requires Nginx or Apache on the machine on which Jenkins is installed.

**Comment by DizzyThermal** [comment]
@rajatsingh25aug 

The OpenShift Template I used to create the Jenkins pod is here: https://gist.github.com/DizzyThermal/675469f95ea6f92988ac1043d714e4ce

This is based on this OpenShift template: https://github.com/openshift/origin/blob/master/examples/jenkins/jenkins-persistent-template.json

The changes made to this template are:
- Converted from JSON to YAML (for readability)
- Increased default Memory and Storage default parameters (2Gi and 10Gi respectively)
- Modified the paths of the livenessProbe and redinessProbe to match the prefix (otherwise, these probes fail)
- Added a `JENKINS_OPTS` env variable with a value of `--prefix=/jenkins`

The env variables section was where I added the `JENKINS_ARGS="--prefix=/jenkins"` you had suggested.

As for my reverse proxy setup, I am using [Ambassador](https://www.getambassador.io/) - a Kubernetes-Native API Gateway that uses **Envoy Proxy**.

My Ambassador deployment YAML is:
```
---
apiVersion: v1
kind: Service
metadata:
  name: jenkins-ambassador
  annotations:
    getambassador.io/config: |
      ---
      apiVersion: ambassador/v1
      kind:  Mapping
      name: jenkins_mapping
      prefix: /jenkins/
      rewrite: /jenkins/
      service: jenkins.jenkins
spec:
  ports:
  - name: jenkins
    port: 80
    targetPort: 8080
```

When using the modified **jenkins-openshift-login-plugin** I built (with the hardcoded `+ "/jenkins" +` added to the OAuthRedirectUrl) everything appears to work - I can login using OpenShift OAuth and navigate Jenkins URLs fine.

My thought was that if somewhere during the building of the Redirect URL we could check if Jenkins had a startup prefix, we could preserve it and make sure the Redirect URL had it between the:
`url.getHost()` and `"/securityRealm/finishLogin"`.

**Comment by gabemontero** [comment]
Hey folks

First, a quick note.  The openshift/jenkins image in no way looks at `JENKINS_ARGS` in launching jenkins.  It does look at `JENKINS_OPTS` as @DizzyThermal noted.

See https://github.com/openshift/jenkins/blob/master/2/contrib/s2i/run#L479-L482

If you are launching jenkins without the openshift/jenkins image, then yeah, I see doc out there about JENKINS_ARGS, but it talks about setting it in /etc/default/jenkins ... bottom line, it is unclear to mean what jenkins will do if there happens to be a env var set in the pod, but we launch jenkins without having `--prefix` as part of the cmd options.

Next,  is such a value available to the login plugin ... if I read https://github.com/jenkinsci/jenkins/blob/master/core/src/main/java/jenkins/model/Jenkins.java#L2256-L2287 correctly, it seems like jenkins.model.JenkinsLocationConfiguration.getUrl() might contain the `--prefix` value.

@DizzyThermal - since you are already hacking on the login plugin code, and given time constraints on my end, would it be possible for you to update your plugin hack to check that value to see if it is what you set for `--prefix`?

Based on the precise results, we can go from there.

**Comment by gabemontero** [comment]
@pradeepto @sthaha @waveywaves fyi ^^

**Comment by DizzyThermal** [comment]
@gabemontero I'll try to get the value of `jenkins.model.JenkinsLocationConfiguration.getUrl()` and see if that contains the `--prefix`.

The prefix value should also be available here: https://github.com/openshift/jenkins-openshift-login-plugin/blob/master/src/main/java/org/openshift/jenkins/plugins/openshiftlogin/OpenShiftOAuth2SecurityRealm.java#L1097

I believe the issue is that when the `redirectUrl` gets passed to `buildOAuthRedirectUrl(...)` a `java.net.URL` is instantiated with that `redirectUrl`, and `url.getHost()` is used to strip the path, here: https://github.com/openshift/jenkins-openshift-login-plugin/blob/master/src/main/java/org/openshift/jenkins/plugins/openshiftlogin/OpenShiftOAuth2SecurityRealm.java#L1116

It seems like [these comments](https://github.com/openshift/jenkins-openshift-login-plugin/blob/master/src/main/java/org/openshift/jenkins/plugins/openshiftlogin/OpenShiftOAuth2SecurityRealm.java#L1110-L1112) suggest that `url.getHost()` is being used to strip the path to get a root URL, but doesn't check if a prefix path should also be appended before the `/securityRealm/finishLogin`.

I'll let you know about `jenkins.model.JenkinsLocationConfiguration.getUrl()` shortly

**Comment by gabemontero** [comment]
On Wed, Apr 17, 2019 at 11:02 AM Stephen <notifications@github.com> wrote:

> @gabemontero <https://github.com/gabemontero> I'll try to get the value
> of jenkins.model.JenkinsLocationConfiguration.getUrl() and see if that
> contains the --prefix.
>
> The prefix value should also be available here:
> https://github.com/openshift/jenkins-openshift-login-plugin/blob/master/src/main/java/org/openshift/jenkins/plugins/openshiftlogin/OpenShiftOAuth2SecurityRealm.java#L1097
>
I suspect that is the entire URL, not just the prefix ... I do not think
trying to infer the presence of a prefix from that will be a good path to
go down

> I believe the issue is that when the redirectUrl gets passed to
> buildOAuthRedirectUrl(...) a java.net.URL is instantiated with that
> redirectUrl, and url.getHost() is used to strip the path, here:
> https://github.com/openshift/jenkins-openshift-login-plugin/blob/master/src/main/java/org/openshift/jenkins/plugins/openshiftlogin/OpenShiftOAuth2SecurityRealm.java#L1116
>
> It seems like these comments
> <https://github.com/openshift/jenkins-openshift-login-plugin/blob/master/src/main/java/org/openshift/jenkins/plugins/openshiftlogin/OpenShiftOAuth2SecurityRealm.java#L1110-L1112>
> suggest that url.getHost() is being used to strip the path to get a root
> URL, but doesn't check if a prefix path should also be appended before the
> /securityRealm/finishLogin.
>
yep understood on all that

> I'll let you know about
> jenkins.model.JenkinsLocationConfiguration.getUrl() shortly
>

great thanks

**Comment by DizzyThermal** [comment]
In the `jenkinsci/jenkins` repo, I found that `StaplerRequest` has a `.getContextPath()` method that appears to provide the `--prefix` needed:
- Example of [creating a mock StaplerRequest with a context prefix of "/jenkins"](https://github.com/jenkinsci/jenkins/blob/84a85225e70a426072cfe53a5313593133ad1bd1/core/src/test/java/hudson/FunctionsTest.java#L96)
- Example of [getting the contextPath from a mocked StaplerRequest, returning "/jenkins"](https://github.com/jenkinsci/jenkins/blob/84a85225e70a426072cfe53a5313593133ad1bd1/core/src/test/java/hudson/FunctionsTest.java#L294)

`StaplerRequest` is a parameter to both [doFinishLogin(...)](https://github.com/openshift/jenkins-openshift-login-plugin/blob/master/src/main/java/org/openshift/jenkins/plugins/openshiftlogin/OpenShiftOAuth2SecurityRealm.java#L1130) and [getPostLogOutUrl(...)](https://github.com/openshift/jenkins-openshift-login-plugin/blob/master/src/main/java/org/openshift/jenkins/plugins/openshiftlogin/OpenShiftOAuth2SecurityRealm.java#L1153) in `OpenShiftOAuth2SecurityRealm`.

Maybe `StaplerRequest` can be used to get this prefix without inferring the presence of a prefix from `Jenkins.getInstance().getRootUrl()` or `jenkins.model.JenkinsLocationConfiguration.getUrl()`.

**Comment by gabemontero** [comment]
On Wed, Apr 17, 2019 at 2:32 PM Stephen <notifications@github.com> wrote:

> In the jenkinsci/jenkins repo, I found that StaplerRequest has a
> .getContextPath() method that appears to provide the --prefix needed:
>
>    - Example of creating a mock StaplerRequest with a context prefix of
>    "/jenkins"
>    <https://github.com/jenkinsci/jenkins/blob/84a85225e70a426072cfe53a5313593133ad1bd1/core/src/test/java/hudson/FunctionsTest.java#L96>
>    - Example of getting the contextPath from a mocked StaplerRequest,
>    returning "/jenkins"
>    <https://github.com/jenkinsci/jenkins/blob/84a85225e70a426072cfe53a5313593133ad1bd1/core/src/test/java/hudson/FunctionsTest.java#L294>
>
> StaplerRequest is a parameter to both doFinishLogin(...)
> <https://github.com/openshift/jenkins-openshift-login-plugin/blob/master/src/main/java/org/openshift/jenkins/plugins/openshiftlogin/OpenShiftOAuth2SecurityRealm.java#L1130>
> and getPostLogOutUrl(...)
> <https://github.com/openshift/jenkins-openshift-login-plugin/blob/master/src/main/java/org/openshift/jenkins/plugins/openshiftlogin/OpenShiftOAuth2SecurityRealm.java#L1153>
> in OpenShiftOAuth2SecurityRealm.
>
> Maybe StaplerRequest can be used to get this prefix without inferring the
> presence of a prefix from Jenkins.getInstance().getRootUrl() or
> jenkins.model.JenkinsLocationConfiguration.getUrl().
>

Perhaps, if it is consistently empty / null when `--prefix` is not set.
Would you have the time to confirm that ?

**Comment by DizzyThermal** [comment]
Yes, I will try and confirm if `StaplerRequest.getContextPath` reflects the value of `--prefix`. I will test with and without `--prefix` being set.

**Comment by DizzyThermal** [comment]
Using the following code snippet:
```java
StaplerRequest req = Stapler.getCurrentRequest();
return url.getProtocol() + "://" + url.getHost() + req.getContextPath()
        + "/securityRealm/finishLogin";
```

`req.getContextPath()` resolves to: `/jenkins`

Currently testing the value when `--prefix` is not set, but since the default prefix for Jenkins is: `--prefix=/` I'm hoping that `req.getContextPath()` resolves to simply: `/` when `--prefix` is not specified.

**Comment by DizzyThermal** [comment]
`req.getContextPath()` resolves to empty string when `--prefix=/` and when `--prefix` is not set.

Maybe something like this could work for both cases (when prefix *is* set and when it *is not*):
```java
final String prefix;
StaplerRequest req = Stapler.getCurrentRequest();

if (req != null) {
    prefix = req.getContextPath();
} else {
    prefix = "";
}

return url.getProtocol() + "://" + url.getHost()
        + prefix + "/securityRealm/finishLogin";
```

**Comment by gabemontero** [comment]
On Wed, Apr 17, 2019 at 4:46 PM Stephen <notifications@github.com> wrote:

> req.getContextPath() resolves to empty string when --prefix=/ and when
> --prefix is not set.
>
> Maybe something like this could work for both cases (when prefix *is* set
> and when it *is not*):
>
> final String prefix;StaplerRequest req = Stapler.getCurrentRequest();
> if (req != null) {
>     prefix = req.getContextPath();
> } else {
>     prefix = "";
> }
> return url.getProtocol() + "://" + url.getHost()
>         + prefix + "/securityRealm/finishLogin";
>
>
Seems plausible.  You up for submitting a PR?

**Comment by DizzyThermal** [comment]
Sure, I want to see if I can add some tests before sending it out. I'll follow up tomorrow

**Comment by gabemontero** [comment]
On Wed, Apr 17, 2019 at 4:59 PM Stephen <notifications@github.com> wrote:

> Sure, I want to see if I can add some tests before sending it out. I'll
> follow up tomorrow
>
Awesome / thanks

**Comment by DizzyThermal** [comment]
@gabemontero created [a PR](https://github.com/openshift/jenkins-openshift-login-plugin/pull/70) with the change suggested above.

Let me know if there's anything you want to see changed, thanks!

**Comment by gabemontero** [comment]
Cool deal @DizzyThermal  ... thanks !!

My to-do list got some unexpected new entries today, so I may not get to the PR review today (and it is a company holiday for use Friday), but if I don't get to the PR review today I will on Monday.

I did ok the regression testing in the PR and tweaked the description so this issue will close automatically when the PR merges.

**Comment by DizzyThermal** [comment]
@gabemontero sounds good to me, thanks!
