### ISSUE TITLE
RedirectUrl omits server-port

### ISSUE THREAD

**Issue by oehmiche** [openshift/jenkins-openshift-login-plugin#78]
First of all: great plugin! - It's very handy to use the openshift authentication for an external jenkins.
Currently our Jenkins server runs on port 8843 (for different reasons). - When using the plugin the server port is omitted in the redirectUrl-parameter when redirecting to openshift (see
https://github.com/openshift/jenkins-openshift-login-plugin/blob/efc9c57958c3e311bdf549d7286b0b178b9dda3d/src/main/java/org/openshift/jenkins/plugins/openshiftlogin/OpenShiftOAuth2SecurityRealm.java#L1192).

Is there a reason for this or is it really an issue?

**Comment by waveywaves** [comment]
It's not really an issue. Are you facing issues with this ?
cc @gabemontero

**Comment by oehmiche** [comment]
> Are you facing issues with this ?
Yes, exactly. - We managed to change the jenkins port to 443.... that fixed our case. But the bug remains in the library.

**Comment by waveywaves** [comment]
@oehmiche I will reproduce this and help you out with this.

**Comment by akram** [comment]
/assign @akram 

Hey @waveywaves , I have assigned it to me and submitted a PR. Could you PTAL ?
