### ISSUE TITLE
OAuth authentication doesn't work with Origin v1.3.x

### ISSUE THREAD

**Issue by danielfn** [openshift/jenkins-openshift-login-plugin#8]
By default, the plugin tries to get the OAuth provider with a request to `.well-known/oauth-authorization-server`. However, this .well-known URI only exists in Openshift Origin starting with the version v1.4.x, therefore with prior versions it fails with a 403 and the message:

```
"message": "User \"system:serviceaccount:myproject:jenkins\" cannot \"get\" on \"/.well-known/oauth-authorization-server\"",
```

**Comment by gabemontero** [comment]
Yes, this is intentional / expected.  I can update the README to clarify, but if you want to use this plugin *without* manually configuring the various parameters, you need to be running against OpenShift Origin v1.4.x in order to obtain the necessary information.

Use of this plugin without configuring it explicitly and against an older version is not supported.

**Comment by gabemontero** [comment]
fyi - I've updated the README.

**Comment by danielfn** [comment]
Seems fair, thanks. I found this problem by using the instant-app Jenkins template which comes with the Ansible installation.

https://github.com/openshift/openshift-ansible/blob/master/roles/openshift_examples/files/examples/v1.3/quickstart-templates/jenkins-persistent-template.json

Here OAuth is enabled by default, so probably it should be better to disable it completely and clarify why -- but that is an issue out of this repo, so I'm closing this one.

**Comment by gabemontero** [comment]
Yeah, the 1.3 version of the template shouldn't be mentioning oauth.  @bparees - do I remember you seeing this as well?

If @danielfn hasn't already done so, I'm going to open a PR to address.

**Comment by gabemontero** [comment]
Opened https://github.com/openshift/openshift-ansible/pull/3138
